const horaceavatarplatformabi = [{"inputs":[{"internalType":"address","name":"_horaceTokenAddress","type":"address"},{"internalType":"address","name":"_horaceAvatarENSAddress","type":"address"},{"internalType":"address","name":"_rentableNFTAddress","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"_owner","type":"address"},{"indexed":false,"internalType":"uint256","name":"tokenId","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"_price","type":"uint256"},{"indexed":true,"internalType":"uint256","name":"_timestamp","type":"uint256"}],"name":"MintNFT","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},{"indexed":true,"internalType":"address","name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},{"inputs":[],"name":"checkHaveRented","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"clearListItems","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"counterAvatar","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"getAllListingItem","outputs":[{"components":[{"internalType":"uint256","name":"mintPrice","type":"uint256"},{"internalType":"string","name":"tokenUri","type":"string"},{"internalType":"bool","name":"isMinted","type":"bool"}],"internalType":"struct HoraceAvatarPlatform.ListingToMintAvatar[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"getContractOwner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"getMintNFTRewards","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"pure","type":"function"},{"inputs":[{"internalType":"string[]","name":"_tokenURI","type":"string[]"},{"internalType":"uint256[]","name":"_price","type":"uint256[]"}],"name":"listToPlatformAvatar","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_id","type":"uint256"},{"internalType":"bool","name":"_royalty","type":"bool"}],"name":"mintNFT","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"payable","type":"function"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"renounceOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"withdrawHAT","outputs":[],"stateMutability":"nonpayable","type":"function"}]

const HoraceAvatarPlatformContract = web3 => {
    return new web3.eth.Contract(
        horaceavatarplatformabi,
        "0x5dA40bBA3e3817193e2A42e5Fb0cB9aDA5BF4Ea3" // horacetoken contract address
    )
}

export default HoraceAvatarPlatformContract